### ISSUE TITLE
Using @ symbol within code under test breaks tests

### ISSUE THREAD

**Issue by toby-griffiths** [phpspec/phpspec#1027]
I'm using the @ symbol within my code under test to test for errors, however PHPSpec runs shutdown after the error handler, even though the error handler does not throw the \PhpSpec\Exception\Example\ErrorException

Is there any way to get around this, or is this just a limitation on how PHPSpec works?

If it helps you suggest an alternative, I'm using the following code to test if an item can be converted to a string…

```
$implodedValue = @implode(',', $value);

if (isset($implodedValue)) {
    return $implodedValue;
}
```

Thanks in advance for any help you can offer

**Comment by stof** [comment]
I don't understand what you mean when saying ``PHPSpec runs shutdown after the error handler``

**Comment by unfunco** [comment]
If you have your `error_reporting` level set to 0, or you're suppressing the error (as you are with `@`) – then the `ErrorException` is not thrown, and so you're presented with an error message like the following:

```
  16  - it implodes
      expected "1,2,3", but got null.
```

Rather than something more helpful, like the following:

```
16  - it implodes
      warning: implode(): Invalid arguments passed in /Users/dmorris/Projects/phpspec-issue-testing/src/Acme/Imploder.php line 
```

The `@` symbol doesn't test for errors, it suppresses them and in most cases is bad practice.

https://github.com/phpspec/phpspec/blob/master/src/PhpSpec/Runner/Maintainer/ErrorMaintainer.php#L124

**Comment by toby-griffiths** [comment]
I realise it should suppress the error from causing the script to terminate, but for some reason, in my case, it didn't, and the script terminated for some reason.  I think I worked around this by refactoring to remove the need for the @, so I'm afraid I can re-test.

**Comment by toby-griffiths** [comment]
Happy to close this as unable to investigate further at the mo.
