### ISSUE TITLE
package does not work with laravel 5.4

### ISSUE THREAD

**Issue by Artistan** [phpspec/phpspec#1060]
https://github.com/laravel/framework/issues/17806#issuecomment-278052149

adding phpspec package causes phpunit to go back to 5.6 and then phpunit testing does not work with laravel.  many details are in this post and on stack overflow..

http://stackoverflow.com/questions/42091495/phpunit-test-failing-phpunit-framework-assert-not-found

**Comment by Sam-Burns** [comment]
PhpSpec 3, which was released early last summer, works fine with recent versions of Laravel.  You may, however, have trouble using brand new versions of PHPUnit and a very old version of PhpSpec, as they both require different versions of `sebastian/exporter`.  I recommend upgrading to a recent version of PhpSpec.

**Comment by unfunco** [comment]
Briefly; I'm not sure this is an issue with phpspec?

The development requirements require PHPUnit `^5.4` which means version 5.7 will be installed if it's available. When running a dependency executable, it should always be run from `vendor/bin` (assuming `bin-dir` hasn't been set to something different) – running just `phpunit` will look for the version that's in your `$PATH` rather than the version installed from the dependency manifest. Also, the version of phpspec in the comments and SO link is the 2.5.x branch, which uses PHPUnit `~4.0` – it looks like there's some confusion rather than an issue.

I will in more detail shortly though…

**Comment by unfunco** [comment]
I've just done the following:

```
~/.composer/vendor/bin/laravel new test
```

That created a Laravel 5.4 application, I then added `"phpspec/phpspec": "^3.2"` to the `require-dev` section of my `composer.json` and ran `composer update` and PHPUnit 5.7 is still the installed version.

```
🍍  composer update
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing phpspec/php-diff (v1.1.0)
    Loading from cache

  - Installing phpspec/phpspec (3.2.3)
    Loading from cache

phpspec/phpspec suggests installing phpspec/nyan-formatters (Adds Nyan formatters)
Writing lock file
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize
Generating optimized class loader

The compiled services file has been removed.

test
🍍  vendor/bin/phpspec --version
phpspec 3.2.3
test
🍍  vendor/bin/phpunit --version
PHPUnit 5.7.11 by Sebastian Bergmann and contributors.
```

**Comment by Artistan** [comment]
thank you for pointing out my confusion. cheers.
