### ISSUE TITLE
Error: must be of the type string, null returned

### ISSUE THREAD

**Issue by roukmoute** [phpspec/phpspec#1083]
Hi!

I've just tested this simple test with PHP 7.1 and phpspec and prophecy in `@dev` version.

```php
public function it_returns_serialized_data()
{
    $this->action()->willReturn('pouet');
}
```

And the signature of `OrderOutPayload::action`:
```php
public function action(): string
```

And each time I get this error message:
```
  15  - it returns serialized data                                                                                                                               
      exception [err:TypeError("Return value of OrderOutPayload::action() must be of the type string, null returned")] has been thrown.
```

Am I missing something?

**Comment by stof** [comment]
``willReturn`` does not make sense on the method of the SUT (``should*`` are what are used). ``willReturn`` makes sense only for calls to collaborators.

And in your case, the call to ``willReturn`` does not even happens. ``$this->action()`` will call the real `action` method of the SUT and wrap the return value. But calling the method seems to fail due to an issue in your own implementation.
Can you show the body of the method ?

**Comment by roukmoute** [comment]
This is my complete test:

Spec:
```php
public function it_returns_serialized_data()
{
    $serializedData = serialize([null, '']);

    $this->action()->willReturn('');

    $this->serialize()->shouldBe($serializedData);
}
```

Class:
```php
public function serialize()
{
    return serialize(
        [
            $this->orderId(),
            $this->action(),
        ]
    );
}

public function action(): string
{
    return $this->action;
}
```

**Comment by avant1** [comment]
You cannot mock methods of class under specification with PhpSpec.
This is intentional limitation that forces you to avoid bad design decisions and generally leads to a more quality code.

Your particular issue seems not to be related to PhpSpec directly. You define that `action()` should return `string`, but seems like you do not initialize `$this->action` with any value, so by default it is `null`.
And when you return `null` from method which should return `string` PHP throws `TypeError`.

So you have several choices:
- give any default value to `$this->action` (like empty string)
- pass the initial value of `$this->action` to constructor of you class (and use `$this->beConstructedWith('default-action-value')` in spec) or set it via setter (don't forget to call setter in spec) if it makes sense
- allow null or string to be returned from `action()` if it makes sense for your application:
```php
public function action(): ?string
```

**Comment by stof** [comment]
you **cannot** use ``willReturn`` on SUT methods, as I said above. ``$this->action()`` in the spec will call the method (which fails because it returns null) and then wrap the value in a Subject instance to allow applying matchers on it.

**Comment by roukmoute** [comment]
Thanks for your responses @stof and @avant1 :smiley: 

I have completely forgotten I can't do what I do and thanks to remind me this :+1:
