### ISSUE TITLE
Issue of creating stub

### ISSUE THREAD

**Issue by bogdan-dubyk** [phpspec/phpspec#1361]
I do not know where to ask this, I made a stackoverflow question already but did not get any answer, I'm not sure I doing it correct and not sure I'm understanding how to write specs correctly :( 

**What I need to test.**

I have a class `SurvyesApi` which is constructed like this (it's php 8 constructor):

```
 public function __construct(
    private HttpClientInterface $httpClient, 
    private LoggerInterface $logger, 
    private string $url, 
    private string $token) {}
```

so in my `SurvyesApi` spec I make a `let` method like this:

I have a wrapper for specific external API which is constructed like this (it's PHP8 syntax thought):
```
   public function __construct(private HttpClientInterface $httpClient, private LoggerInterface $logger, private string $url, private string $token) {}
```
so spec for this class constructed like this:

```
    private static string $token = 'token';
    private static string $url = 'url';
    
    public function let(HttpClientInterface $httpClient, LoggerInterface $logger): void
    {
        $this->beConstructedWith($httpClient, $logger, self::$url, self::$token);
    }
```

all looks correct for me in this point.

Now `SurvyesApi` has mehtod `getSurvyes` which should:
1. make API call to get surveys
2. for each surveys make a call to get targetings and make call to get quotas, to make this process faster I'm making those calls async
3. associate related quota and targetings to each survey
4. return surveys

Here is a code (a bid simplified I omit all the validation etc.)

```
public function getSurveys(): array
{
    $surveysResponse = $this->httpClient->request(
            'GET',
            $this->url . 'getSurveysUrl',
            [
                'headers' => [
                'x-access-token' => 'token',
            ]
        ]);

    $targetingResponses = [];
    $quotaResponses = [];
    $surveys = [];
    foreach($surveysResponse as $survey) {
         $surveyObject = Survey::fromRespone(survey);
         $targetingResponses[$surveyObject->getIdentifier()] = $this->httpClient->request(
            'GET',
            $this->url . 'getTargetingsUrl' . $surveyObject->getIdentifier(),
            [
                'headers' => [
                'x-access-token' => 'token',
            ]
         ]);
         $quotaResponses[$surveyObject->getIdentifier()] = $this->httpClient->request(
            'GET',
            $this->url . 'getQuotasUrl' . $surveyObject->getIdentifier(),
            [
                'headers' => [
                'x-access-token' => 'token',
            ]
         ]);

       $surveys[] = surveyObject;
    }
     // those calls for targeting and quota async so now we need to get actuall responses
     foreach ($surveys as $survey) {
         $targetingResponse = $targetingResponses[$survey->getIdentifier()])->toArray();
         $quotaResponse = $quotaResponses[$survey->getIdentifier()])->toArray();
         $survey->assoicateTargetings(new Targetings(targetingResponse));
         $survey->assoicateQuotas(new Quotas(quotaResponse))
     }

     return $surveys;
}
```

and I want to create a spec like `it_should_return_surveys_if_all_surveys_valid()`

Here is the spec I made:

```
public function it_should_return_surveys_if_all_surveys_valid()
{
    // make a call to get surveys, in this case only 1 survey
    $surveysResponse = [
        'apiStatus' => 'success',
        'result' => [
            // it's a builder class I made to not pass huge array to each spec
            (new SurveyArray())->build(),
        ]
    ];
    $surveyId = surveysResponse['result'][0]['surveyId'];
    $response->toArray()->shouldBeCalled()->willReturn($surveysResponse);

    $httpClient->request(
        'GET',
        self::$url . 'getSurveysUrl',
        [
            'headers' => [
                'x-access-token' => self::$token,
            ]
        ]
    )->willReturn($response);

   // make a call to get targetings

   $targetingResponse = []; //response here, I omit it as it's not not important here
   $response->toArray()->shouldBeCalled()->willReturn($targetingResponse);

   $httpClient->request(
        'GET',
        self::$url . 'getTargetingsUrl' . $surveyId,
        [
            'headers' => [
                'x-access-token' => self::$token,
            ]
        ]
   )->willReturn($response);

  // make call to get quotas

   $targetingResponse = []; //response here, I omit it as it's not not important here
   $response->toArray()->shouldBeCalled()->willReturn($quotaResponse);

   $httpClient->request(
        'GET',
        self::$url . 'getQuotasUrl' . $surveyId,
        [
            'headers' => [
                'x-access-token' => self::$token,
            ]
        ]
    )->willReturn($response);

    $survey = Survey::fromRespone($surveysResponse['result'][0]);
    $survey->associateQuotas(new Quotas($quotaResponse['result']));
    $survey->associateTargeting(new Targetings($targetingResponse['result']));

    $this->getSurveys()->shouldReturn([$survey]);
}
```

And here is a 2  issues:
1. for some reason it's making `getQuotasUrl` call as a first call not a `getSurveysUrl`, what I'm doing wrong?
2. I have a feeling that this spec is too complicated, probably I think in a wrong direction, more in unit testing way? Can some one please provide an example how to test such a logic correctly???

**Comment by gquemener** [comment]
Not sure if it helps but here's my 2 cents:

In my experience, the fact that you have this feeling is the intent of PhpSpec (example should be straight forward and possible to read flawlessly) and I personnaly use it as a modeling heuristic.

Given the reading complexity of your `it_should_return_surveys_if_all_surveys_valid` example, I would tend to think that you're doing too much in your `getSurveys` method.
I would suggest to introduce something like an api client object which would encapsulate the http communication logic, instead of passing by a full featured http client, for example.

Once you have managed to simplify your example, and if it's still failing without reason, I would suggest to copy/paste the full output of the execution, so we have a better understanding of what PhpSpec is telling you.

Regards.

**Comment by bogdan-dubyk** [comment]
> I would suggest to introduce something like an api client object which would encapsulate the http communication logic, instead of passing by a full featured http client, for example.

you mean to encalupsulate logic like this?

**Comment by gquemener** [comment]
Are you familiar with the concept of "Do not mock what you don't own"? FYI, that's the principle (not a rule) on which I based my suggestion to encapsulate the http communication logic.

Furthermore, you don't need to use both `shouldBeCalled` and `willReturn` methods on your mock. If the method is not called it will not return the specified value. `willReturn` implies that the method is called. Your example should fail if it is not.

PhpSpec is built from the BDD principle, which is derived from TDD. Here's a simple exercise : try to imagine that you don't have implemented the `getSurveys` method. Would you be able to write the `it_should_return_surveys_if_all_surveys_valid` example?
It seems to me that you're writing the example after writing the implementation.

Your issue is probably coming from a mock which is wrongly specified, that is the reason why I suggest you to move away the real 3rd party http client complexity. Once you've done that, either pass it a concrete, in-house, implementation (built for testing and not making any real http call), or use a mock, that's up to you.

Real life http communication could be tested through an integration test.

Having a look at subjects like "hexagonal architecture" might help you as well if you're not already familiar with the concept.

> is there some specific options I should pass to the command to see useful output?

The ones that make the output verbose is enough.

Regards.

**Comment by bogdan-dubyk** [comment]
> Are you familiar with the concept of "Do not mock what you don't own"? FYI, that's the principle (not a rule) on which I based my suggestion to encapsulate the http communication logic.
> Having a look at subjects like "hexagonal architecture" might help you as well if you're not already familiar with the concept.

I agree it make sense to use "hexagonal architecture" and I use it (I use onion but it basically all the same) for other services, but this service is basically 4 classes, and to not overcomplicate it I did not make own http abstraction. But probably you are right and I already made it, did not check if it works yet.

> PhpSpec is built from the BDD principle, which is derived from TDD

I know this and yeah in this case realization was written before I considered to use phpspecs, all new code will be written following TDD/BDD principles

I'm a bit short in time this  days, when I done with refactoring I'll let you know if it works. Thank you very much !
