### ISSUE TITLE
Ask whether to generate a class or an interface for collaborators/doubles

### ISSUE THREAD

**Issue by damonjones** [phpspec/phpspec#341]
In the pursuit of best practises, you will often want to typehint against interfaces instead of classes (especially in the case of collaborators/doubles, where you may not have even written an implementation).

Would it be possible/desirable to ask the user if they want a class or an interface? Or would something similar to the approach in #339 (using a configuration option in the phpspec.yml file) be reasonable (if you always favour generating interfaces over classes)?

**Comment by bfolliot** [comment]
👍I'd like to see this feature @damonjones

**Comment by everzet** [comment]
I'm not sure I like the idea of promoting (even if by proxy) the mocking of classes. I like the current behaviour where every collaborator starts as an explicit protocol (interface) rather than specific implementation. Everything is a protocol and I believe decision to convert an interface into a specific implementation at the generation phase is a premature commitment.

I'd rather prefer a feature where when you're describing (`phpspec describe MyInterface`) something that already exists as an interface, PhpSpec would suggest you to convert it into particular implementation.

**Comment by tomphp** [comment]
Since I last thought about this, I've come to thinking of things the way @everzet has just described - I can't remember the last I wanted to create a real instance from a mocked collaborator.

Therefore, I'm now 👎  for this feature.

**Comment by ciaranmcnulty** [comment]
I'm happy with interface generation for now
