### ISSUE TITLE
Partial mock

### ISSUE THREAD

**Issue by tabbi89** [phpspec/phpspec#474]
The problem is when I try to pass unWrappedObject

``` php
use Knp\Menu\FactoryInterface;
use Knp\Menu\ItemInterface;
use Knp\Menu\MenuItem;
# ...
function it_matches_menu(ItemInterface $menu, FactoryInterface $factory)
    {
        $url = 'test';

        $menuArr = [
            'category' => $menu
        ];

        $root = new MenuItem('root', $factory);
        $root->setChildren($menuArr);

        $this->match($root, $url);
    }
```

And I get fallowing error:

<pre>
error: Argument 2 passed to Knp\Menu\MenuItem::__construct() must implement interface Knp\Menu\FactoryInterface,
      instance of PhpSpec\Wrapper\Collaborator given, called in
</pre>

**Comment by stof** [comment]
IMO, the real issue is that you are trying to use a spec for something which should actually be an integration test rather than a unit spec. The KnpMenu classes are not under your own control, so you should avoid mocking them (your spec does not ensure your class work, as you cannot be sure that your mock actually reflects the behavior of the external library)

**Comment by eddiejaoude** [comment]
Thank you for the feedback @stof :+1:
