### ISSUE TITLE
Test __constructor with/without exception

### ISSUE THREAD

**Issue by huglester** [phpspec/phpspec#574]
Hello,

I have a success testing something like this:

``` php
public function it_handles_exception_for_an_array()
{
    $this->shouldThrow('InvalidArgumentException')->during('__construct', [[]]);
}
```

but how do I actually test, that the __constructor did not return an exception?

``` php
public function it_validates_numeric_3()
{
    $this->beConstructedWith(['zzz']);
}
```

but the tests pass, but in general with this value Exception was thrown. is there a way to ensure, that
there was no Exception?

Thanks

**Comment by docteurklein** [comment]
First, I'm sorry to discuss on an old, closed card ( and if you want me to open a new one I will), but this issue seems to perfectly match my case.

I understand that testing only the constructor without testing other methods seems strange, but phpspec behavior is very strange too :)

Given this class:

```php
class Test
{
    function __construct() {
        throw new \Exception;
    }
}
```

and its corresponding spec:


```php
namespace spec\App\Domain;

class TestSpec extends \PhpSpec\ObjectBehavior
{
    function it_is_initializable()
    {
        $this->shouldHaveType('App\Domain\Mailer');
    }
}
```

Then the test suite should **definitely** fail.

Shouldn't it?

Currently, as @stof pointed, you have to add a strange `$this->getWrappedObject()`; coming of nowhere.

I perfectly understand the reasons behind this, but it still is very surprising at first :)
I think there is something to do here.

**Comment by docteurklein** [comment]
like, maybe we could instantiate it before any `should*` if it wasn't instantiated already?

**Comment by ciaranmcnulty** [comment]
You are describing a situation where code exists already and you want to write a failing test for it - this is not TDD.

Start with no constructor, write the following:

```
$this->shouldThrow('Exception')->duringInstantiation();
```

This will fail. Make it green by adding the constructor that throws.
