### ISSUE TITLE
Smarter example name matching and splitting to end the wars

### ISSUE THREAD

**Issue by Dragonrun1** [phpspec/phpspec#608]
As many of you know there are three main coding naming conventions:

snake_case
camelCase
PascalCase

and everyone has an opinion on which is best which has been know to turn into flame wars on forums, around water coolers, etc when brought up. I'm not here to say that phpspec was right or wrong in going with snake_case for examples in specs but to offer another way of looking at it and possible end any battles at least as far as phpspec is concerned. So why not allow the developers using phpspec to decide which they prefer in their own project? This can be done without adding any settings or anything but simply by making phpspec a little bit smarter when it is loading the examples. Let's do a little digging into how phpspec currently finds, loads, and enforce the naming convention in the spec examples before getting on to my _better_ way.

__Code BackGround__
Phpspec uses ```ResourceLoader::load()``` to find, load, split up the spec files into Specifications and Examples. On line 69 is where it determines of it thinks a method is an example as should here:
```php
if (!preg_match('/^(it|its)[^a-zA-Z]/', $method->getName())) {
```
Just so everyone understands it the RegEx will match any string starting with 'its' or 'it' followed by a non-alphabetical character. So for some examples to show things it would _not_ match:

```
itsShould...
itShould...
ItsShould...
IDoNotMatch...
```

and ones that do:

```
its_should_...
it_should_...
its_Should...
its0001...
```

Some of you probably are surprised by the last couple of allowed names but they would be allowed given the current RegEx that phpspec uses. I think this was not intended and they simply were trying to insure that camel case or pascal case names didn't match. For those of you wondering the following RegEx is better at allowing only what was intended ``'/^(it_|its_)/'``. There is only one other place where the use of snake case vs something else comes into play in phpspec and it is in the same ``load()`` method on line 78 as seen here:
```php
$example = new Node\ExampleNode(str_replace('_', ' ', $method->getName()), $method);
```
It uses a simple ``str_replace()`` to make the ``_`` into a space instead. This is done to make it into a more human readable form used by the output formatters. These couple of lines are the only thing that causes phpspec to currently require the use of underscore case vs anything else. So now that we understand some background on how little phpspec really cares one way of the other it let me show you what I think is a _better_ way.
 
__A Better Way__

So as I showed above phpspec only cares or enforce any requirements for spec example names in a couple line of ```ResourceLoader::load()```. These would be the only lines that need to change so you can use pascal or camel case, or any other thing you can think of instead. So what is my _better_ way? Simple change phpspec so it doesn't care what the developers choose to use as long as it can find the spec examples. It does this already for spec file and class names with the only requirement being the spec class file name be the source class name with ``Spec.php`` added and that the spec class name be also the source class name with ``Spec`` on the end. It aslo requires that it implements the ``PhpSpec\SpecificationInterface`` just so it knows how to work with it. My way does much the same thing for the spec example names by simply expecting any method in the spec class that starts with 'Its', 'It', 'its', or 'it' to be an example it should do something with. Here's what line 69 would look like
```php
if (!preg_match('/^[Ii](?:ts|t)/', $method->getName())) {
```
A quick explanation of the Regex is it will match any name that begins with an upper or lower case 'i' followed by either 'ts' or 't'. Some examples of things it would match:

```
its_should...
it_should...
ItsShould...
itShould...
It0001Should...
```

And something it would not would be 'IShouldNotMatch'. So it'll match anything that meets the minimum requirement to be considered a spec example and ignore the rest. What about line 76 where the example name need to be split up into words?
```php
$example = new Node\ExampleNode(ucfirst($this->smartExampleNameSplitter($method->getName())), $method);
```
The ``str_replace()`` has been replaced with a call to the private method ``smartExampleNameSplitter()``. Here is the method as well:
```php
private function smartExampleNameSplitter($name)
{
    if('_' === $name[2] || '_' === $name[3]) {
        return str_replace('_', ' ', $name);
    }
    $split = preg_split('/(^[^A-Z]+|[A-Z][^A-Z]+)/', $name, null, PREG_SPLIT_NO_EMPTY | PREG_SPLIT_DELIM_CAPTURE);

    return strtolower(implode(' ', $split));
}
```
So just a quick walk through on how works. it starts by looking for a ``_`` character at the second or third position in the string and if it finds one it replaces them all using ``str_replace()`` and returns the new string. If the string doesn't have any ``_`` where it expected ithem it'll assume camel or pascal case, or something like them and start split the string into an array of words. It will then put the words back together with spaces in between and finally lower cases the whole string to be returned. One more thing you may have noticed on line 76 is the ``ucfirst()`` I added as well. The reason is I noticed with all the formatters is they didn't do this even though the idea was to make the class name into something more human friendly and even more sentence like but they ignored this simple thing so I decided to fix that little nit here even though it would probably be better somewhere in the formatters themselves. So now that I've covered the how and where technical parts I'll talk a little more about the why.

__Why Should Phpspec Care?__

Actually that's really my point it shouldn't care past what it needs to to do what it's job. Since it the new kid on the block it needs to finds ways to be included and not do things that can keeps people from wanting to use it. I'll take my personally experience of trying to get started with phpspec as an example.

I first heard about phpspec about a year or so ago and start looking into it to see what it might have to offer. I'd already tried Behat a year or two before that and found it just wasn't useful for any of the projects I was involved in at the time because basically most of the stakeholders weren't really accessible to me and they were already mid-life projects. I did see some promise in the ideas behind BDD and TDD in general vs what I had done before so I decided to try it out on some new projects. Since most of my projects tend to be programs for programmers I've found that Behat just isn't really a good fit and will leave it for projects where I'm doing stuff for non-programmers etc in the future.

On to phpspec which once I really understood it was a developer tool and not just another testing tool I started tried it on a couple small projects. First big hurtle with phpspec is find out that it uses a domain language. Those of you that know it might find it hard to believe but its not clear that one exist and how important it is. The existing docs do little to help since they don't ever bother to include a simple listing of what all the commands and verbs are or any kind of cheat-sheet that are so very useful when learn something new. The first cheat-sheet I ran across was http://petersuhm.com/blog/phpspec-matchers-cheat-sheet but I've also found https://github.com/yvoyer/phpspec-cheat-sheet helpful. One of them or something like them  needs to be put directly in the phpspec docs along with some better examples. So on the first project I stumbled through writing a spec after fighting for way to long and finally just giving up on editing the configuration to get the specs in the directories I wanted to use and the namespace right.

Next issue I ran into is I do use camelCase for methods and have switched to FIG's psr-1 and some of psr-2 standards in my own projects because it was the most similar to what I had done before plus my preferred IDE (PhpStorm) included some preset for them like most editors and IDE do now to help you with the little stuff like this. Some people like using stand alone tools as well  to check the coding style and I've even worked on projects with others where they had it as part of their pre-commit scripting to check code styles, run unit tests etc and reject anything that didn't pass. Now something all of these other tools have in common is they expect the whole project to use a single style. There's for a good reason for that because if you are using more than one style in different parts of the project why are you even worry about checking it's right everywhere? Doesn't make a lot of sense to me or them to do that so it's not an option. Note the difference here in that all the other tools I am using changed to suit me and the project being worked on they didn't try force me or anyone else to their way of thinking beyond using something and sticking to what you choose.

So to sum up my first couple of tries with integrating phpspec into my work flow was I ended up dropped it and stayed with the stuff I found useful and which didn't add any additional, what I felt was pointless obstacles, in my path when trying to using them.

I've read a post by one of the developer of phpspec a while back where he said that they would consider making changes if someone could come up with good reason why they should use something else. I see it differently in that phpspec like any new kid on the block or camel at the tent flap you need to take the first small steps. You may get invite to play with others or stick your head in the tent but if you don't make an effort to fit in you'll end up always just looking in from outside after they kick you out and start ignore you. I would really hate to see phpspec stay on the sidelines or only be used by a small group of 'cool' kids when it has so much more to bring into PHP development cycle for many programmers and help improve software for everyone. But first it has to want to be used by more people by not adding extra obstacles that make people less willing to give it another chance. Hopeful if my changes are included in the the main project from my pull request it will help in some small way to the what I'm sure is the original developers dream for it to be used by most if not all PHP programmers.

**Comment by everzet** [comment]
Hi Michael,

Thank you very much for such an expanded research and comment. Let me try to answer some key points of it :)

> I'm not here to say that phpspec was right or wrong in going with snake_case for examples in specs but to offer another way of looking at it and possible end any battles at least as far as phpspec is concerned.

There have been no battles around which case to use for quite some time. I'd attribute it to the fact that people **don't really** care about conventions and consistency if breaking conventions or consistency actually helps you be more expressive or clear in your living documentation.

> So why not allow the developers using phpspec to decide which they prefer in their own project?

Because PhpSpec was created and still evolves as "highly opinionated tool". Our goal was not to chase ever increasing user-base, our goal was to help others do what we always wanted to do more effectively. Choice in this case not only wouldn't help, it would diverge from the set by us path. Choice is a tool, which you use when you have no idea which option is the best. In this particular case, based on countless training, coaching and pairing sessions, I'm pretty certain in saying "snake_case" is still a much better option for spec example naming.

> This can be done without adding any settings or anything but simply by making phpspec a little bit smarter when it is loading the examples.

I know :) As a matter of fact, the reason behind PhpSpec not supporting camelCase is not a technical limitation. It is deliberate, and highly biased towards readability, decision. We match for `it_*` methods instead of `it*` on purpose, because we believe that different, more expressive naming in this case appeals to the different mindset! As much as PhpSpec is a TDD tool, it is an education tool for us. We use it to teach people be more effective and happy with TDD. Sometimes it takes breaking conventions.

> Why PhpSpec should care? Actually that's really my point it shouldn't care past what it needs to to do what it's job. Since it the new kid on the block it needs to finds ways to be included and not do things that can keeps people from wanting to use it. I'll take my personally experience of trying to get started with phpspec as an example.

You're working from assumption that we need to find ways to be included. Inclusivity and pursue of the bigger market share is not of our interest. We actually want to create a tool that will both help us in doing and teaching TDD. How much do we help people to do TDD is a much more important metric to us than how much people use our tools.

> First big hurtle with phpspec is find out that it uses a domain language. Those of you that know it might find it hard to believe but its not clear that one exist and how important it is. The existing docs do little to help since they don't ever bother to include a simple listing of what all the commands and verbs are or any kind of cheat-sheet that are so very useful when learn something new.

I know guys are hard at work at improving docs. Improving documentation is an ongoing fight we need to fight, but we'll get there. In the mean time, any help is extremely welcome: https://github.com/phpspec/phpspec2-site.

> Next issue I ran into is I do use camelCase for methods and have switched to FIG's psr-1 and some of psr-2 standards in my own projects because it was the most similar to what I had done

Breaking you out of conventions is part of what we're trying to do. When you're coming up with an example, we want to remove all safety nets like naming rules. Conventions are invaluable when you're working in the domain of **best practices** (your general code). We believe that specs actually live in the domain of **good practices**, where doing things right is more important than doing things conventionally. On the IDE/tool side of things - every tool I know of allows you to easily setup ignore paths where it runs checks. I see absolutely no reason to run any checks except "is it readable?" against your specs or features. Conventionality is not really a metrics you should go for there.

> So to sum up my first couple of tries with integrating phpspec into my work flow was I ended up dropped it and stayed with the stuff I found useful and which didn't add any additional, what I felt was pointless obstacles, in my path when trying to using them.

You made the right call. It seems you needed a tool that **fits your workflow**, in most cases it's not PhpSpec :) To reiterate - PhpSpec has exactly two goals:

1. Help people be more effective and happy with TDD
2. Teach people how to do TDD right

Fitting people's workflow or being able to adapt to them is not the goal. If anything, in most cases drastically changing your workflow is the only way to be more effective with TDD. And that's again, intentional.

> I've read a post by one of the developer of phpspec a while back where he said that they would consider making changes if someone could come up with good reason why they should use something else. I see it differently in that phpspec like any new kid on the block or camel at the tent flap you need to take the first small steps.

I hope at this point I did clarify that "being new kid on the block" or "make an effort to fit in" is not really a good reason for us. We're really looking at different metrics.

---

Please, don't be discouraged by my response. Not every tool will fit the way you see the world at specific moment in time, nor they should. It is totally fine that your workflow at the moment is not compatible with what PhpSpec tries to do. It does not necessary mean that you do something wrong, it also doesn't necessary means that tool does something wrong. It simply means that at this moment in time we have different priorities :) Put tool in the shelf and return back to it, when these two match.

Thank you!

**Comment by stof** [comment]
> I know guys are hard at work at improving docs. Improving documentation is an ongoing fight we need to fight, but we'll get there. In the mean time, any help is extremely welcome: https://github.com/phpspec/phpspec2-site.

@everzet  Actually, this repo is totally deprecated (not updated since one year). the docs are now in the phpspec repo itself and rendered on ReadTheDocs. this is also why I asked several times whether @MarcelloDuarte had transferred the DNS ownership to @ciaranmcnulty so that we can finally get it to point to the uptodate documentation (see #448). And the docs are now actually a lot better than the docs rendered on phpspec.net (and they describe available matchers for instance): http://phpspec.readthedocs.org/

**Comment by everzet** [comment]
@stof oh, ok. Missed that. Even better :)

**Comment by ciaranmcnulty** [comment]
Wow thanks for the detailed response @everzet. I agree on all points.

@dragonrun1 you could consider making this an extension for your own use perhaps?

**Comment by Saeven** [comment]
I know this is old, for what it's worth, when you are plugged into something like Codacy and are enforcing PSR-2, which includes PSR-1, which has that method names must be declared in camel case...  we are forced into a situation where we have to ignore the bundle folders that contain phpspec tests.

It'd be nice if we did indeed have the option to comply with PSR-1 when using phpspec.  The two streams don't seem that divergent.  I feel ignoring spec files isn't optimal.

_Seems common-sensical that if it is in a phpspec test, and starts with it_ or it[A-Z] one can be pretty damned sure it's intended to be a test._

Thanks though, for a stellar component.
