### ISSUE TITLE
Will return array($mocked); causes issues.

### ISSUE THREAD

**Issue by bweston92** [phpspec/phpspec#666]
The following code throws an error because "$offer" in the Collection (or even if I just pass as an array) isn't ready? I don't know but when my code called `$offer->getCreatedAt()` it returns a `MethodProphecy` object.

(DOESN'T WORK)

```
    public function it_can_get_locked_time(DealInterface $deal, OfferInterface $offer, $offers)
    {
        $time = Carbon::now();

        $offer->getCreatedAt()->willReturn($time);
        $offers->withStatus('PENDING', 'COMPLETE', 'ACCEPTED')->shouldBeCalled();
        $offers->getByDeal($deal)->willReturn(Collection::make([$offer]));

        $this->locked($deal)->shouldBe([
            'status' => 'locked',
            'complete' => true,
            'completed_at' => (string) $time,
        ]);
    }
```

Yet without being in an array (another example) WORKS.

```
    public function it_can_get_funded_time(DealInterface $deal)
    {
        $time = Carbon::now();

        $deal->funded()->willReturn(true);
        $deal->getFundedAt()->willReturn($time);

        $this->funded($deal)->shouldBe([
            'status' => 'funded',
            'complete' => true,
            'completed_at' => (string) $time,
        ]);
    }
```

**Comment by peterjmit** [comment]
@bweston92 You are missing a call to `getWrappedObject`

```php
$collection = Collection::make([$offer->getWrappedObject()])
$offers->getByDeal($deal)->willReturn($collection);
```

**Comment by bweston92** [comment]
I managed to do that yeah, but why isn't it required for the others? I love magic but this magic is hidden. Also this isn't documented anywhere.

**Comment by ciaranmcnulty** [comment]
The fundamental problem here is that PhpSpec can deal with two different types of parameters to method calls:

 * Doubles, with stubbed methods that return either doubles or real values
 * Real values containing real values

There is a third category that is not handled, and we don't have a good strategy to handle is:

 * Real values containing doubles

This is because we have no way of intercepting the call to the real object and 'unwrapping' the returned double; this is why you have to call `getWrappedObject()` in those cases. (and of course we have no way to unwrap in your array example).

Any suggestions about how to make this clear in the docs without confusing people would be welcome (or maybe a way to handle the errors more cleanly)

**Comment by stof** [comment]
not that ``array($offer)`` will be unwrapped automatically by PhpSpec, by replacing the array. However, for objects, it does not know how to unwrap doubles used internally, because there is no way to do this in a generic way (and btw, in many cases, you will already have an issue with a typehint when building your object).

**Comment by ciaranmcnulty** [comment]
yes, sorry, it's the make() that is causing the issue
