### ISSUE TITLE
Windows: 'PHPSPEC_EXECUTION_CONTEXT' is not recognized as an internal or external command, operable command or batch file

### ISSUE THREAD

**Issue by javi-dev** [phpspec/phpspec#773]
### The issue

On Windows systems, after succesfully auto-generating code, this error message is shown on the command prompt.

> 'PHPSPEC_EXECUTION_CONTEXT' is not recognized as an internal or external command, operable program or batch file.

I have tested this on my Windows 10 machine and a fresh Windows 7 VirtualBox installation, with only php 5.6.13 and composer installed.

![phpspec_execution_context](https://cloud.githubusercontent.com/assets/3085310/9822875/46e5b3fe-58c3-11e5-8c3f-228763862431.png)

On an Ubuntu system, the message doesn't appear.

### Versions affected

PhpSpec 2.3.0

### Versions unaffected

PhpSpec 2.2.1

### Steps to reproduce

1. Get a Windows machine with php/composer installed.

2. Create an empty folder.

3. `composer require phpspec/phpspec`

4. Set psr-0 autoloading, `composer dumpautoload`, etc.

5. `phpspec describe Test`

6. `phpspec run`

7. Test will fail, PhpSpec will offer to create the class for the user. Answer Y.

8. PspSpec will create the class, but the above mentioned error will be shown.

Same error message when creating a method.

### My findings

Keep in mind that I'm a noobish programmer, and this codebase is overwhelming to me.

What I've found is that an afterSuite event is fired, and ClassNotFoundListener will mark
the test as "worth rerunning". Then, ReRunListener afterSuite() will be called, will check
if the test is worth rerunning, and then rerun the suite. From there, it will end in the
PassThruRerunner reRunSuite() method, which will build a string to rerun the suite. And there
lies the problem: to build the command, it calls a buildArgString() method. This method gets
an executionContext of JsonExecutionContext (the only implementation of the interface AFAIK), and 
asEnv() returns an array, being the key the infamous 'PHPSPEC_EXECUTION_CONTEXT' that confuses Windows, and a Json string. So the method returns this long string…

`PHPSPEC_EXECUTION_CONTEXT="{ generated-types :[ Test ]}"`

…which then gets concatenated to the php executable path, and the arguments, and that is executed by the system via passthru(). Windows doesn't like that.

Now, if I remove the `$this->buildArgString()` part of the `$command` string, everything seems to work fine, but it's obviously there for a reason, so I guess the problem lies elsewhere, but I don't know how to continue from there.
 
Which is where my noobishness shows, and the reason why this is an issue and not a pull request :)

### Questions

Now, questions:

1. Is someone else able to reproduce this, or have I a botched php/phpspec installation or whatever? I'm surprised nobody has complained already.

2. PhpSpec works fine, the error message is annoying but I can live with it. But the question is:
Do I keep trying to understand what's wrong, or maybe someone more clever than me already has the answer?

3. Should I start using Unix-like systems for coding and not even noticing errors like these and live a happier life?

I'll be glad to help with whatever you may need from me. Thanks!

**Comment by avant1** [comment]
Answering your questions:

> Is someone else able to reproduce this, or have I a botched php/phpspec installation or whatever? I'm surprised nobody has complained already.

I've reprodused this issue on win7 with *phpspec 2.3*, version *2.2* works fine.
I am using windows as my main OS, but usually I use Vagrant for development, there are some older projects runned on windows, but they used *phpspec 2.2*, so I haven't faced this problem before.

> PhpSpec works fine, the error message is annoying but I can live with it. But the question is:
Do I keep trying to understand what's wrong, or maybe someone more clever than me already has the answer?

Quick look at the code found several problems.
Generated command passed to *passthru()* on windows looks like
```cmd
PHPSPEC_EXECUTION_CONTEXT="{ generated-types :[ Test ]}" C:^\WebServers^\usr^\local^\php^\php.exe "c:\WebServers\home\phpspec-win-bug\vendor\bin\/../phpspec/phpspec/bin/phpspec" "run"
```

Here phpspec tries to set env variable and then rerun itself. Problems:
* Windows thinks that PHPSPEC_EXECUTION_CONTEXT is a path to binary, it doesn't find this and fails with error on screenshot. Correct way to set env variable for session is to use [SET] (https://www.microsoft.com/resources/documentation/windows/xp/all/proddocs/en-us/set.mspx?mfr=true) command. 
* Generated json with types worth to be rerunned contains double quotes (because it is json :smile: ), but according to [php.net] (http://php.net/manual/en/function.escapeshellarg.php)
> On Windows, escapeshellarg() instead removes percent signs, replaces double quotes with spaces and adds double quotes around the string.

so json becomes invalid.

* Even if we add `SET` before env variable name and solved problem with quotes, and command will look like
```cmd
SET PHPSPEC_EXECUTION_CONTEXT={"generated-types":["Test"]} C:^\WebServers^\usr^\local^\php^\php.exe "c:\WebServers\home\phpspec-win-bug\vendor\bin\/../phpspec/phpspec/bin/phpspec" "run"
```
then SET command will think that everything that goes after `=` is value of env variable. So we should tell CMD that this is two commands. And command becomes (note `&&` between commands).

```cmd
SET PHPSPEC_EXECUTION_CONTEXT={"generated-types":["Test"]} && C:^\WebServers^\usr^\local^\php^\php.exe "c:\WebServers\home\phpspec-win-bug\vendor\bin\/../phpspec/phpspec/bin/phpspec" "run"
```
This command finally works as expected.

So rerun command format should be changed on windows, and json could be encoded again (with `base64_encode` for example) to work on windows. Probably after this fixes everything will work fine on Windows.
Feel free to try yourself and to create pull request. If you will face difficulties you can always ask questions.

> Should I start using Unix-like systems for coding and not even noticing errors like these and live a happier life?

It sounds like a good idea, but no one should tell you what to do :smile:. Probably most of developers use unix-like systems (Linux or Mac), but also there are developers who use Windows. 
Tools like Vagrant allow you to work on Windows with projects which should be runned on linux (still there can be windows-specific problems). 
Small projects without complex environment can be developed on windows. And *phpsec* generally supports Windows.

Anyway you can try both and pick OS you like more for development.

**Comment by ciaranmcnulty** [comment]
Thanks for the report @javi-dev, and the analysis @avant1 

This new feature clearly doesn't work on Windows - unfortunately we don't have a CI environment that can detect these problems.

It might be possible to hide the error on Windows, but unfortunately the intention is to use this environment for more in future.

I'll see if I can get a Windows environment to test in, I guess.

**Comment by javi-dev** [comment]
@avant1 Thank you for confirming the bug. I usually use Vagrant/Homestead, and I'm even toying with Docker, but this was a quick and dirty "I'm learning phpspec!" project… that ended up with me digging through phpspec's own code, and the project is not even started :D

Also, thank you again for your detailed explanation, I feel like I'm learning lots of interesting things. I'm afraid I still don't know enough about the feature (Why the env variable? Won't this changes to the code break other systems? Etc.) to submit a PR, and it seems to me that @ciaranmcnulty has plans in mind for the feature.

@ciaranmcnulty Sorry for giving you more work ;)

**Comment by ciaranmcnulty** [comment]
@javi-dev the feature is that when a class definition is generated and written to disk, we pass the name of the class as an env variable to the next execution.

This is used so that if the class is not found on the next execution, we can tell the user they have probably got a broken autoloader rather than trapping them in a loop of being prompted a 2nd time to generate the class.

There are also plans to use this context for more in future so it's good to iron the issue out now.

**Comment by javi-dev** [comment]
Oh, I understand now. I've been in the classic yellow loop before (more times than I would like to admit). I'll keep digging, for funsies, it's not like I had nothing better to do this weekend.

**Comment by ciaranmcnulty** [comment]
Would be very happy to see a PR, @avant1's suggestions look solid

**Comment by chrisemerson** [comment]
I am looking at this at the moment, and have got it working, but don't like the solution I currently have. I have an additional issue with my setup as well because my PHP executable is in a path with a space in it, which also throws an error even once the environment variable issue is solved. I'll see where I get and open a PR if I work it out!

**Comment by chrisemerson** [comment]
I've opened a PR for this, linked above.
