### ISSUE TITLE
Programatically create mocks in spec tests

### ISSUE THREAD

**Issue by sagikazarmark** [phpspec/phpspec#777]
I need a large number of mocks in a test. Is it possible to create them using prophecy without using injection in the test method?

Something like:

`$mock1 = $this->prophesize('MyClass');`

**Comment by mheki** [comment]
Hi @sagikazarmark 
PhpSpec has some limitations, but encourages some good practices while designing the code.
"Large number of mocks" sound like a design smell. How about reducing number of collaborators?

However, you can still use PhpUnit for these doubles in the way you described.

**Comment by ciaranmcnulty** [comment]
You can use Prophecy by directly instantiating a Prophet, as described in its docs https://github.com/phpspec/prophecy. 

Because PhpSpec did not generate the Double directly, you'll need to call `checkPredictions` explicitly in the spec to check everything happened as expected.

However @mheki is right, the correct choice is probably to reduce the number of collaborators your object has.

**Comment by sagikazarmark** [comment]
Well, "large number of mocks" means three or four PSR7 RequestInterface. We are testing parallel execution where the point is that there are multiple requests.

Thanks for the answers.
