### ISSUE TITLE
Zend_mm_heap corrupted

### ISSUE THREAD

**Issue by roelmonnens** [phpspec/phpspec#785]
I've created a repo on github to explain what I'm encountering.

https://github.com/roelmonnens/phpspecissue

**Comment by GrahamCampbell** [comment]
Is that not just a bug in php 5.6.12?

**Comment by stof** [comment]
This should be reported to PHP, not to PhpSpec. ``Zend_mm_heap corrupted`` means there is an issue in PHP itself (or in a C extension).

and btw, you should try the same on PHP 5.6.14 first, to know whether they fixed it already or no. and also try it by disabling your extensions, to see whether you can identify an extension causing this.

**Comment by roelmonnens** [comment]
Ok will try it

**Comment by GrahamCampbell** [comment]
Do you have xdebug installed. That might be causing this? Just a wild guess. It could be anything, and I don't know a lot about the internals.

**Comment by ciaranmcnulty** [comment]
On my machine your example causes the memory limit to be reached, somewhere inside Prophecy.

It's not clear to me why this might happen.

**Comment by nick-jones** [comment]
@ciaranmcnulty - For me it OOMs (memory_limit=1G) at [phpspec/prophecy/src/Prophecy/Util/ExportUtil.php:145](https://github.com/phpspec/prophecy/blob/master/src/Prophecy/Util/ExportUtil.php#L145) (specifically the call into `print_r`). The `$value` it is trying to dump is particularly large; this is due to a trace being present in this case, as PHP is building this on `Exception` construction. There are a good number of references to the `ObjectProphecy` instance for the `Exception` double within the trace arguments, so ultimately when it's dumping these, it has a ton of stuff to get through (including going through the trace again in each case). I suspect this is why it's exhausting memory..

If this is indeed the case, then perhaps phpspec/prophecy#121 will fix this? There is no longer a `print_r` present in [sebastianbergmann/exporter](https://github.com/sebastianbergmann/exporter), so maybe the existing problem calling for a `print_r` to be used has been solved in a different fashion.

@roelmonnens - `Class LoggerInterface not found` - that is probably due to PHPDoc being left in place without the full qualified class name in the `@param` tag.

**Comment by ciaranmcnulty** [comment]
I'm closing this as the PR in Prophecy seems like it will solve it.
