### ISSUE TITLE
Option to filter specs

### ISSUE THREAD

**Issue by dantleech** [phpspec/phpspec#925]
As with the PHPUnit `--filter` option.

```bash
$ # run all specs starting with `it_should_do_that`
$ phpspec run --filter="it_should_do_that"
$ # run all specs containing "foobar"
$ phpspec run /path/to/spec/MySpec.php --filter="foobar"
```

I often use this feature in PHPUnit to execute only one test. This allows better isolation when debugging.

**Comment by ciaranmcnulty** [comment]
If your use case is to run just one test, you can achieve this by referencing the line number

`phpspec run /path/to/spec/MySpec.php:102`

I'd be open to a more generic filter mechanism if there are more use cases than this.

**Comment by avant1** [comment]
As for filter by example name - personally I am not sure if it would be very helpful for locating specs because:
- Running single example using line number (as @ciaranmcnulty shown) is probably *simplier* way, cause we already have failing example line number in output.
- Isolating several related examples for debugging usually is not needed, because with `phpspec` you usually do not store any state of your application, you just check if behavior of single subject class follows specification (at least, `phpspec` forces you to write specs in that way). Correct me if I am wrong.
- Specs usually _run quickly_ (my personal execution time record is about 20 seconds for 1k+ examples on dev machine), so you can just rerun whole class on namespace specs and receive quick feedback.
- For grouping specs we already have `suites`, it is probably more reliable way to rerun set of specs using suites instead of example name fragment.

But this functionality may be implemented in extension.

**Comment by dantleech** [comment]
Ah OK, I didn't realise you could specify a line number, running a single spec really is my sole use case. in that case this can be closed.

Do you think it would be worth adding the a line number example to the default PHPSpec CLI help?

```
Help:
 The run command runs specifications:
 
   php ./bin/phpspec run
 
 Will run all the specifications in the spec directory.
 
   php ./bin/phpspec run spec/ClassNameSpec.php
 
 Will run only the ClassNameSpec.

   php ./bin/phpspec run spec/ClassNameSpec.php:102
 
 Will run only the spec at line 102 of ClassNameSpec
```

**Comment by ciaranmcnulty** [comment]
Certainly, it also seems to be missing in the docs.

I'll close this and open a documentation issue 👍
