### ISSUE TITLE
Ignore Exception

### ISSUE THREAD

**Issue by roukmoute** [phpspec/phpspec#965]
I would like to know it is that possible to ignore an `Exception` in method and force to use `willReturn` method ?

I have an example:

In theory, the Transformer must have the same name of the entity (via `this->getClassName`)
But in this case, how can I do because my `SimpleEntity` and `TransformerInterface` are not the same.

```php
class JsonViewTransformer
{
    private $transformers = [];

    public function testTransformer(View $view)
    {
        $entity = $view->getData();
        $this->getTransformerFromEntity($entity);
    }

    public function addTransformer(TransformerInterface $transformer)
    {
        $this->transformers[$this->getClassName($transformer)] = $transformer;
    }

    private function getTransformerFromEntity($entity)
    {
        $entityName = $this->getClassName($entity);

        if (!array_key_exists($entityName, $this->transformers)) {
            throw new ClassNotFoundException(sprintf('%s does not exist', $entityName), new \ErrorException());
        }

        return $this->transformers[$entityName];
    }
    
    private function getClassName($object)
    {
        $FQCNObject = get_class($object);
        $objectName = substr($FQCNObject, strrpos($FQCNObject, '\\') + 1);

        return $objectName;
    }
}
```

In the test file:

```php
function it_returns_json_from_tranformer(View $view, SimpleEntity $entity, TransformerInterface $transformer)
{
    $entity->getId()->willReturn(1);
    $entity->getName()->willReturn('foo');
    $entity->getAge()->willReturn(42);

    $transformer->transform($entity)->willReturn([
        'id',
        'name',
        'age',
    ]);

    $view->getData()->willReturn($entity);

    $this->addTransformer($transformer);
    $this->testTransformer($view);
}
```

So I've got this error message:
```
  15  - it returns json from tranformer
      exception <label>[exc:Symfony\Component\Debug\Exception\ClassNotFoundException("P1 does not exist")]</label> has been thrown.
```

Have you an idea for this kind of problem?

**Comment by avant1** [comment]
If I understand the code correctly, the error you see ("P1 does not exist") is because of the fact that `$view` variable in 
```php
function it_returns_json_from_tranformer(View $view, SimpleEntity $entity, TransformerInterface $transformer)
```
is not actually instance of class `View`. It is an collaborator in terms of `phpspec`. 
And `JsonViewTransformer::testTransformer` will not receive `View` object as parameter, it will receive a special object of generated in runtime class with name like `Double\View\P1`.

And when you extract name of  `$view` you receive `P1`, and there is no transformer for `P1` (there will be transformer for `P3` (incrementing counter is used for collaborators), cause when you add transformer, it is not transformer too, but one of those automatically generated classes).
All this magic is needed to make phpspec working.

So relying on class names is not the best path when using phpspec. I'm not sure if it can be easily fixed when using collaborators.

But you can add method `supports(View $view)` to ``TransformerInterface``, which will check if transformer supports transforming of given `$view`. You can start with simple `instanceof` check inside it.

In fact, that approach will be much more flexible and less fragile. You can rename transformers without necessity to rename corresponding view class. You don't need to track naming collisions (if classes with the same name are defined under different namespaces).
It will be more easy to change logic of transformer choice in future.

So, phpspec is forcing you to write reliable and safe code.

**Comment by ciaranmcnulty** [comment]
What @avant1 said ;-)

The class passed in is a double, so `get_class` will be returning its internal type.
